name: gh-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: jekyll build
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: |
            Blog updated. https://owky.github.io/blog/
            Commit Message: ${{github.event.head_commit.message}}
            GitHub Action: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}